<?php
/**
 * Implements hook_form_alter().
 */
function beannotitle_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'bean_form') {
    $selected_bean_types = variable_get('beannotitle_bean_types');
    if ($selected_bean_types[$form['#bundle']] === $form['#bundle']) {
      $form['title']['#default_value'] = '<none>';
      $form['title']['#prefix'] = '<span class="element-hidden">';
      $form['title']['#suffix'] = '</span><p>' . t('Title field is hidden via the Bean - No Titles module') . '</p>';
    }
  }
}

function beannotitle_menu() {
  $items['admin/config/content/beannotitle'] = array(
    'title' => 'Bean - No Title',
    'description' => 'Configure which Block Types will automatically have their Title field set to "<none>" and hidden.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('beannotitle_admin'),
    'access arguments' => array('access content'),
    'file' => 'beannotitle.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}
